### PR TITLE
Utils, lists

### PR DESCRIPTION
**Pull request by muskan-gupta-0803**
- added utility components and docs
- added list components and docs

### CODE REVIEW

**Review by dev-enforced — APPROVED** [review]
The code looks good to me. Good work on documenting the utils and lists !!Well structured CSS classes

**Review by yogesh- — APPROVED** [review]
Looks good to merge.

**Comment by muskan-gupta-0803** [comment]
> The code looks good to me. Good work on documenting the utils and lists !!Well structured CSS classes

thankyou for the review

**Comment by muskan-gupta-0803** [comment]
> Looks good to merge.

thanks for reviewing.

**Pull request merged**
